apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak

spec:
  type: LoadBalancer
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8081 #put this back to 8080 when running on aws
      targetPort: 8080 
      protocol: TCP
